# Generated by Django 5.2.15 on 2026-06-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
