# Generated by Django 6.0.6 on 2026-06-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_seeker_avatar_alter_seeker_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
    ]
