# Generated by Django 6.0.6 on 2026-07-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_seeker_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employer',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
